Nuitka/Nuitka

nuitka/freezer/DependsExe.py

Added better error handling and informational messages around installing Dependency Walker in an offline setting.

Dependency Walker Installation Tweaks

---

nuitka/freezer/Standalone.py

real diff:
```diff
$ git diff -b -w
diff --git a/nuitka/freezer/Standalone.py b/nuitka/freezer/Standalone.py
index d0a68393..4c3c241c 100644
--- a/nuitka/freezer/Standalone.py
+++ b/nuitka/freezer/Standalone.py
@@ -558,6 +558,8 @@ _detected_python_rpath = None
ldd_result_cache = {}
def _detectBinaryPathDLLsLinuxBSD(dll_filename):
+    if ldd_result_cache.get(dll_filename):
+        return ldd_result_cache[dll_filename]
result = set()
@@ -575,7 +577,6 @@ def _detectBinaryPathDLLsLinuxBSD(dll_filename):
os.path.dirname(sys.executable).encode("utf-8")
)
-    if dll_filename not in ldd_result_cache:
with withEnvironmentPathAdded("LD_LIBRARY_PATH", _detected_python_rpath):
process = subprocess.Popen(
args   = [
@@ -635,8 +636,6 @@ def _detectBinaryPathDLLsLinuxBSD(dll_filename): …
```

fix(freezer: Standalone): create an exit from recursion

---

CONTRIBUTING.md
README.rst
bin/autoformat-nuitka-source
bin/check-nuitka-with-pylint
bin/check-nuitka-with-pylint3
bin/check-nuitka-with-restlint
bin/compare_with_cpython
bin/measure-construct-performance
bin/nuitka
bin/nuitka-run
bin/nuitka3
bin/nuitka3-run
bin/sort-nuitka-import-statements
doc/digital_art/3D/instructions.txt
doc/nuitka-man-include.txt
requirements.txt

This fixes several typos in documentation and comments which I notices while getting familiar with the project.

Fix several typos all over the place.

---

nuitka/nodes/ImportNodes.py

Makes a ignorant attempt to fix a syntax error.
#159

fix: getFullName double append

---

nuitka/utils/FileOperations.py

Fix a small issue when half of the dependency cache path exists, hence makedirs will try to create it all and may fail.
No relevant issues, just less annoying when playing with dependency cache files.
Not applicable
Not applicable

Existing cache dir fix

---

README.rst

Document the PE file internal dependency walker.
Not applicable

Pe file doc

---

README.rst

This PR fixes the [Isort Project link](https://github.com/Nuitka/Nuitka#projects-used-by-nuitka) in README.rst

Fixed the Isort project link in README.rst

---

Developer_Manual.rst

Fix developer manual typo

---

Developer_Manual.rst

Corrected some typos and few punctuations to make the document more readable and look more professional.
- [] All tests still pass. Check the developer manual about ``Running the Tests``. There
- [] Ideally new features or fixed regressions ought to be covered via new tests.
- [] Ideally new or changed features have documentation updates.

Updated Developer_Manual.txt

---

README.rst

Added a short guide/tutorial for setup and testa on windows using mingw compiler.

Short guide to installation and testa Windows

---

misc/make-dependency-graph.py
nuitka/build/SingleExe.scons
nuitka/freezer/Standalone.py
nuitka/importing/Importing.py
nuitka/importing/PreloadedPackages.py
nuitka/importing/StandardLibrary.py
nuitka/nodes/ModuleNodes.py
nuitka/optimizations/Optimization.py
nuitka/plugins/standard/ImplicitImports.py
nuitka/plugins/standard/PmwPlugin.py
nuitka/tools/quality/ScanSources.py
nuitka/tools/quality/autoformat/Autoformat.py
nuitka/tools/quality/isort/__main__.py
nuitka/tools/release/Debian.py
nuitka/tools/release/Documentation.py
nuitka/tools/release/Release.py
nuitka/tools/release/bump/__main__.py
nuitka/tools/release/pypi/__main__.py
nuitka/tools/release/sync_doc/__main__.py
nuitka/tools/testing/Common.py
nuitka/tools/testing/SearchModes.py
nuitka/tools/testing/Valgrind.py
nuitka/tools/testing/measure_construct_performance/__main__.py
nuitka/utils/Shebang.py

- Fix several `ResourceWarning: unclosed file`
- Also uniformaize the use of the "with" context manager when dealing with files.
Wanted to shut down noisy warnings in my console. Don't know if you are interested in fixing them, but I try :)
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

Fix several ResourceWarning: unclosed file

---

Developer_Manual.rst
UserPlugin-Creation.rst
Using-Plugin-Options.rst
doc/Doxyfile
nuitka/Options.py
nuitka/plugins/Plugins.py
nuitka/plugins/standard/NumpyPlugin.py
nuitka/plugins/standard/TkinterPlugin.py
tests/standalone/TkInterUsing.py

Enable options for user plugins

---

Developer_Manual.rst

Improve slots example

---

Developer_Manual.rst
UserPlugin-Creation.rst
Using-Plugin-Options.rst
doc/Doxyfile
nuitka/plugins/PluginBase.py
nuitka/plugins/Plugins.py
nuitka/plugins/standard/NumpyPlugin.py
nuitka/plugins/standard/TkinterPlugin.py
py-file.bat
py-file.sh

Changed the documentation format back to standard Python ``__doc__`` style. This affects the 3 previously documented plugin modules `TkinterPlugin.py`, `NumpyPlugin.py` and `PluginBase.py`.
There are no active code changes in these modules.
After locating package `doxypypy`, which is able to transform Python ``__doc__`` into `doxygen` format, we are switching to this solution for a number of obvious good reasons.
This entailed a minor change to `doc/Doxyfile` which now will use a filter to preprocess Python sources by invoking `doxypypy`.
**Before …

Improve Plugin documentation

---

README.rst

fixed small errors

---

Developer_Manual.rst

fix the sys.meta_path file name in developer manual

---

tests/type_inference/Test4.py

I am not sure, why it is left incomplete (I hope it's not intentional), I tried making a minor change which will do the intended work for us.
Thank you for contributing to Nuitka!

Test4.py is incomplete

---

tests/optimizations/Operations.py

Finished writing functions for all the operations that were mentioned in the TODO list.
Thank you for contributing to Nuitka!

Added functions for all the mentioned operations

---

tests/basics/TrickAssignments32.py
tests/basics/TrickAssignments35.py

List of new tests added
--------------------------------
Also updated inplace matmul in py35.

Tests: Cover more Trick Assignments tests

---

README.rst

I have updated Readme.rst and fixed almost all the typos and corrected minute punctuation mistakes to make it look more legible as well as nicely structured.
Thank you for contributing to Nuitka!
are Travis tests that cover the most important things, however, and you are welcome to rely on those, but they might not cover enough.

Updated Readme.rst

---

UserPlugin-Creation.rst
Using-Plugin-Options.rst
nuitka/Options.py
nuitka/importing/Recursion.py
nuitka/plugins/standard/ImplicitImports.py

Add basic "scipy" package support in ImplicitImports plugin

---

nuitka/plugins/standard/PySidePyQtPlugin.py
tests/standalone/PyQt5SSLSupport.py

Add the OpenSSL support on Windows within Qt applications.

Standalone: Include OpenSSL DLLs for PyQt apps on Windows

---

nuitka/plugins/standard/NumpyPlugin.py

Also added support for scipy as an option to this plugin.
Copying any additional binaries has been moved to the end of the compile.
- Changed `plugin_name` from "numpy-plugin" to "numpy" following a recommendation of @kayhayen.
- Added scipy support as an option like this: ``--enable-plugin=numpy=scipy``.
- Also added copying undetectable scipy DLLs (Windows only), similar to what had been done already for numpy.
- Moved the process of copying binaries: this will now happen when the distribution folder is otherwise finished (i.e. in …

Change "numpy-plugin" to just "numpy"

---

tests/basics/TrickAssignments32.py

I added some more tests to Nuitka/tests/basics/TrickAssignments32 where was a comment with TODO. Also made "__int\__" method return anobject of type ```int``` instead of ```bool``` as I was getting warning while running tests.
I just wanted to make a contribution to take one of Nuitka's projects as my GSoC project and while examining code I saw this TODO comment and found out that this job is suitable for me.(I'm sorry if that was the job of someone else, but the file haven`t been changed for 26 days, so I decided to try)

Cover more trick assignments

---

tests/standalone/RsaUsing.py

This is done by testing the encryption and decryption
components of the rsa package.
Basically, it involves the creation of a public/private
key pair which is used to encrypt a given message using
the public key, sends it to the recipient and uses the
private key to decrypt the encrypted message at the
receiving end.
An assertion is used to check that the message stays the
same after the encryption-decryption process.
Algorithm
=========
- Create Private/Public key pair
- Encode with UTF-8 and encrypt the message then send
- Decrypt the message and decode it using UTF-8
- Assert to make sure the message at the receiving end
matches what was sent.
create (priv/pub) key ---> encode and encrypt message
---> decrypt and decode message ---> assert message
Signed-off-by: tab1tha …

[TEST] RSA PyPI standalone test for Nuitka

---

nuitka/distutils/bdist_nuitka.py
tests/distutils/example_2/package1/main.py
tests/distutils/example_2/package1/module1.py
tests/distutils/example_2/package1/module2.py
tests/distutils/example_2/package1/subpackage1/data.txt
tests/distutils/example_2/package1/subpackage1/submodule11.py
tests/distutils/example_2/package1/subpackage2/submodule21.py
tests/distutils/example_2/runner
tests/distutils/example_2/setup.py

Fixes #337 
While testing bdist_nuitka, by passing custom options to nuitka via setup.py script.
No documentation yet, @kayhayen let me know where to add the documentation in the user manual.
Maybe sections https://github.com/Nuitka/Nuitka#write-some-code-and-test and https://github.com/Nuitka/Nuitka#use-cases documenting bdist_nuitka would be a nice place, with a couple of examples also with custom nuitka options ?
I also have some tests, but the tests/bdist/run_all.py are failing, I'll try to check if something's wrong in my setup, when I'm able to execute …

fix for issue  #337

---

nuitka/plugins/standard/DataFileCollectorPlugin.py
nuitka/plugins/standard/ImplicitImports.py

Add support for both pycryptodome and pycryptodomex packages (previously, only pycryptodomex was supported)
Tested with both packages, compiled program works great out of the box.
https://github.com/Nuitka/Nuitka/issues/215
Not applicable
Not applicable

Add support for both pycryptodome and pycryptodomex

---

README.rst

change in Manual (Windows install)

---

nuitka/plugins/standard/NumpyPlugin.py

See https://github.com/Nuitka/Nuitka/pull/399

Fix NumpyPlugin path case issues

---

nuitka/Tracing.py
nuitka/distutils/bdist_nuitka.py
tests/distutils/multiple_packages/main_module.py
tests/distutils/multiple_packages/other_package/__init__.py
tests/distutils/multiple_packages/other_package_a/__init__.py
tests/distutils/multiple_packages/runner
tests/distutils/multiple_packages/setup.py
tests/distutils/multiple_packages/some_package/__init__.py
tests/distutils/multiple_packages/some_package_a/__init__.py
tests/distutils/multiple_packages/some_package_b/__init__.py

Add `Distutils` support for wheels with multiple top level packages.
Address #571, #527, and makes a compromise for #530

Distutils: Add support for distinct package namespaces

---

nuitka/plugins/PluginBase.py

Improve documentation
When I first read this, I searched for the "UserPlugin" class which doesn't exist ;)
- [N/A] Ideally new features or fixed regressions ought to be covered via new tests.
- [N/A] Ideally new or changed features have documentation updates.

User plugin derivation should happen from NuitkaPluginBase class

---

README.rst

Improve documentation about library dependencies used in standalone compilation.
Discussion #603
- [N/A] Ideally new features or fixed regressions ought to be covered via new tests.
- [N/A] Ideally new or changed features have documentation updates.

Instructions for Visual C runtimes on standalone compilation

---

nuitka/Tracing.py
nuitka/freezer/BytecodeModuleFreezer.py

See title.
Fixes #640.
I would need help doing this.

Fix to not have KeyError: 'style' when building

---

nuitka/utils/SharedLibraries.py

Fixes a minor issue causing crash when architectures mismatch
Because I bumped into an issue. Didn't create an issue about it.

Fix issue with warning in getPEFileInformation

---

nuitka/tools/release/Documentation.py
nuitka/utils/Execution.py

`subprocess.check_call` will raise an exception if a command fails.
This shortens the code in this module significantly and delegated
the work to subprocess.check_call.
As discusses in #674.

Remove assertion of exist status 0 in favor of check_call

---

Developer_Manual.rst

typo for PEP 8 compliance

---

.vscode/extensions.json

Remove a duplicate in .vscode/extensions.json.
No issue, I saw this while reading the file.
No code is really changed here, so the tests were no re-launched.

remove duplicate VS Code extension recommendation

---

tests/standalone/run_all.py

tests: Ignore /usr/etc/

---

Changelog.rst

Changelog.rst: Fix link to PySide2 support

---

nuitka/plugins/standard/ImplicitImports.py

fixes using pyreadstat with --standalone (issue #980)

pyreadstat

---

nuitka/plugins/standard/ImplicitImports.py

Add support for automatically adding tzdata to the required imports when using exchangelib

Add support for exchagelib

---

nuitka/Options.py
nuitka/PythonVersions.py
nuitka/build/Backend.scons
nuitka/build/SconsInterface.py
nuitka/build/static_src/MainProgram.c
nuitka/importing/StandardLibrary.py
nuitka/tools/quality/autoformat/Autoformat.py
nuitka/utils/FileOperations.py
nuitka/utils/Utils.py
nuitka/utils/WindowsResources.py

Implements a static Windows build using the Nuitka-Python fork.
cover enough.

Nuitka-Python Integration with Windows Static Build

---

nuitka/plugins/standard/ImplicitImports.py

Add the implicit imports of overrides for Gtk etc.
I'm not sure if this is the way to go?
If so, probably some more imports need to be added or made more selectively.
In an attempt to provide a fix for #769.
cover enough.

Include Gtk overrides

---

nuitka/build/Backend.scons

Use LTO and PGO for NuitkaPython.
cover enough.

Use LTO and PGO for NuitkaPython.

---

nuitka/plugins/standard/PkgResourcesPlugin.py

This PR adds support for `pkg_resources.require` calls in the `pkg-resources` plugin.
Since these calls are meant to raise an exception at runtime, my take is to raise the exception at Nuitka compilation if requirement isn't met, and suppress the statement if it is met.
Currently `pkg_resources.require` raises an exception when compiled by Nuitka, even with the `pkg-resources` plugin.
cover enough.

Add support for pkg_resources.require calls

---

nuitka/MainControl.py
nuitka/OptionParsing.py
nuitka/Options.py
nuitka/build/Backend.scons
tests/benchmarks/pystone.py

Performs PGO on the Nuitka-generated code. 
Greatly improved performance. 
cover enough.

Added option to use PGO on Nuitka-generated code.

---

README.rst

Kay, as per one of our conversations, I thought maybe it'd be worth mentioning this install in an Anaconda environment?
Thanks,
Abe

Update README to reference libpython-static installation

---

nuitka/utils/FileOperations.py

add alternative for distutils.dir_util.copy_tree

---

nuitka/plugins/standard/data-files.yml
nuitka/tools/testing/Common.py

Fix #1275 cv2 import config.py module failed
cover enough.

Optimization, #1275 cv2 import config.py module failed

---

Developer_Manual.rst

While going through the doc in search of a solution for my problem, I stumbled upon a few typos.

Small stylistic changes

---

nuitka/plugins/standard/implicit-imports.yml

see https://github.com/python/cpython/blob/3.9/Lib/zipfile.py#L2040

support `py_compile`

---

nuitka/build/inline_copy/lib/scons-4.3.0/SCons/Script/Main.py
tests/distutils/example_2/setup.py
tests/distutils/example_3/setup.py
tests/distutils/py_modules_only/setup.py

Fix typo in word 'always'

---

.vscode/extensions.json
nuitka/Reports.py
nuitka/plugins/PluginBase.py
nuitka/plugins/standard/ImplicitImports.py
nuitka/plugins/standard/OptionsNannyPlugin.py
tests/standalone/run_all.py

and add recommendation for jinja2 extension

check for unknown tags

---

nuitka/build/Backend.scons
nuitka/build/SconsInterface.py
nuitka/freezer/Standalone.py
nuitka/plugins/standard/DllFilesPlugin.py

This PR implements the Nuitka-Python linkup for Linux to pull the proper list of libraries to link to.
cover enough.

Implement linux build with Nuitka-Python.

---

.vscode/settings.json
misc/nuitka-package-config-schema.json
nuitka/plugins/standard/ImplicitImports.py
nuitka/plugins/standard/standard.nuitka-package.config.yml
nuitka/plugins/standard/stdlib2.nuitka-package.config.yml
nuitka/plugins/standard/stdlib3.nuitka-package.config.yml

- move the implicit imports from ImplicitImport.py to the yaml files
- fix schema
- add schema-check for stdlib2 and stdlib3

Move the implicit imports from plugin to yaml

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

Adds datafiles required for pyenchant spellchecker package

Standalone: Added datafiles needed for "pyenchant" package

---

nuitka/build/static_src/CompiledCodeHelpers.c

For all platforms (tested on Linux, Windows and macOS), adds a mechanism to resolve any symbolic links in the path of the executable when determining the directory of the binary. 
For all POSIX like systems, this makes use of `realpath()` to fully resolve the path. On Windows similar is achieved with `GetFinalPathNameByHandle()` (with a W suffix for `wchar` support.)
Without this, loading of bundled dynamic libraries and Python package resources will fail if a symbolic link that points to the executable file is used since Nuitka currently sets the Python directory to that of the link itself, not the file the link targets.
This change allows, for example, a dist directory built in `--standalone` mode to be deployed to a system in an arbitrary location and a symbolic link created to the …

Resolve symbolic links to the executable binary

---

nuitka/build/Backend.scons

Handles export-dynamic linker flag when using clang.
#1759 
cover enough.

Added export-dynamic linker flag for clang

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

Updated LooseVersion checks in anti bloat config
Ref: https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/compat/numpy/function.py#L114
Generated binary with pandas (1.1.x or 1.0.x) dependency fails because of unknown variable LooseVersion.
```
...
File "/tmp/onefile_3195_1661613946_529738/pandas/__init__.py", line 52, in <module pandas>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "/tmp/onefile_3195_1661613946_529738/pandas/core/api.py", line 15, in <module pandas.core.api>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File …
```

Added Pandas compatibility for >= 1.0.0

---

nuitka/build/Backend.scons
nuitka/freezer/DllDependenciesMacOS.py

[Contributing Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md)
Add support for Nuitka-Python to set link (and compile) flags.
Also fix an issue that caused Nuitka to not find dlls that python is linked to.
cover enough.

Add support for Nuitka-Python to set link flags.

---

nuitka/tools/quality/auto_format/YamlFormatter.py

YAMLFormatter: change standard quote to single

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add support for sv-ttk

---

nuitka/BytecodeCaching.py
nuitka/ModuleRegistry.py
nuitka/Reports.py
nuitka/importing/Importing.py
nuitka/importing/Recursion.py
nuitka/nodes/ImportNodes.py
nuitka/tree/Building.py
nuitka/tree/Operations.py
tests/standalone/Urllib3Using.py

report missing modules

---

tests/standalone/run_all.py

Related to https://github.com/Nuitka/Nuitka/issues/1972
cover enough.

Tests: Dont enable numpy plugin

---

nuitka/importing/Importing.py

- reduce call of `isdir` in `getModuleNameAndKindFromFilename`
This PR is unfinished

compile time optimizations

---

nuitka/importing/Importing.py
nuitka/importing/Recursion.py

remove code duplication and remove invalid ToDo

---

nuitka/MainControl.py

I have closed PR #2002 by error. In this pull request i have made the changes that @kayhayen suggested in that PR.

Added check for zstandard before compilation when onefile

---

nuitka/tools/testing/OutputComparison.py

Fixes https://github.com/Nuitka/Nuitka/issues/2011

Tests: Ignore ld info output

---

nuitka/freezer/Standalone.py
nuitka/plugins/Plugins.py

Fixes https://github.com/Nuitka/Nuitka/issues/2016

Plugins: Fix removeDllDependencies

---

README.rst

I noticed a place in README.rst where the "Note"  was not working, so I fixed it.

Modify the "Note" in README.rst

---

Changelog.rst
debian/changelog
doc/Doxyfile.template
nuitka/build/static_src/HelpersAttributes.c
nuitka/build/static_src/OnefileSplashScreen.cpp
nuitka/plugins/standard/standard.nuitka-package.config.yml
tests/basics/BuiltinsTest.py
tests/basics/ExceptionRaisingTest.py
tests/basics/ExecEvalTest.py
tests/basics/TrickAssignmentsTest32.py
tests/basics/TryExceptFramesTest.py
tests/basics/YieldFromTest33.py
tests/benchmarks/pybench/CommandLine.py
tests/benchmarks/pybench/pybench.py
tests/benchmarks/pybench/systimes.py
tests/distutils/example_1/setup.py
tests/distutils/example_cfg_1/setup.py
tests/distutils/py_modules_only/setup.py

Corrects various typos found in the repository.
No, just some clean-ups.
cover enough.

Correct some typos

---

.gitignore
nuitka/plugins/standard/standard.nuitka-package.config.yml

added a warning
#2071
cover enough.

added warning for `attrs` version

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

This pull request add an implicit dependency of the sqlalchemy package
This PR fix issue #2262

Added sqlalchemy implicit dependency

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

This pull request add the wordlist data dir of the mnemonic package
This pull request solves issue #1966

Added mnemonic data dirs

---

nuitka/Options.py

Make nuitka check for `termux-elf-cleaner` in Termux.
https://github.com/Nuitka/Nuitka/issues/2341
cover enough.

Termux onefile check command termux-elf-cleaner.

---

nuitka/Options.py

Make clang the termux default compiler
https://github.com/Nuitka/Nuitka/issues/2341
cover enough.

Make clang the termux default compiler

---

nuitka/build/static_src/HelpersFilesystemPaths.c

This patch fixes support for Haiku.
cover enough.

Fix Haiku support

---

Developer_Manual.rst

While reading the developer manual I stumbled over what I think is a typo - this might be what was intended instead?

Tryfix developer manual typo

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

Add missing font file for [qtawesome](https://pypi.org/project/QtAwesome/)
fix #2543

Add missing font file for qtawesome

---

nuitka/OptionParsing.py
nuitka/Options.py
nuitka/build/Backend.scons
nuitka/build/CCompilerVersion.scons
nuitka/build/Onefile.scons
nuitka/build/SconsCompilerSettings.py
nuitka/build/SconsInterface.py

Enable integration with other third parties by selecting -fcf-protection for the GCC compiler, allowing you to choose the right trade-off between security and performance. 
#2603 

Added select -fcf-protection mode for the GCC compiler

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

fixes error due to missing DLL with kiwisolver

added kiwisolver missing DLL

---

nuitka/plugins/standard/ImplicitImports.py

fix improper yield that could lead to crash

---

nuitka/plugins/standard/OptionsNannyPlugin.py

Fixes two very minor grammar mistakes in OptionsNannyPlugin.py
I saw one while testing in tkinter and wants to contribute the fix.

fix grammar in OptionsNannyPlugin.py

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

added pillow implicit dependency for imageio
added missing datafiles for easyocr
fixes #2659

Imageio / easyOCR

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add scipy missing npz data file

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

speech_recognition missing executables

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

include needed gmsh dll

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

added support for `cryptoauthlib`, fixes #1106
added `betterproto` missing datafile  fixes error found in #1476
added data file needed by `tracerite` fixes issue brought up once #1579 is compiled
added data file needed by `sklearn.utils`
added various data files needed by `qt_material` # fixes #1666

various yaml additions

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add scapy support

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

support pypdfium2

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

include toga_winforms metadata

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add support for gruut

---

nuitka/tools/testing/Common.py

📈 Performance improved by **`36%`** (**`0.36x` faster**)
⏱️ Runtime went down from **`1416.20μs`** to **`1040.40μs`**
<details>
<summary>(click to show)</summary>
I updated the original function to calculate the indent space (`" " * count`) before the loop, storing it in the variable `indent` and then used it inside the generator expression. The indentation used to be calculated for each line of the code. This change makes the program more efficient because the string multiplication operation is done only once before the loop and not for each line in `codes`. Now, the time needed to process larger files is reduced, particularly when adding a larger number of spaces. The generator expression 'lazily' constructs the string for each line, using less memory when working with larger inputs. …

⚡️ Speed up `indentedCode()` by 36% in `nuitka/tools/testing/Common.py`

---

Changelog.rst

Update Changelog link

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add libmagic support

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

fix: pyocd work entirety
https://github.com/Nuitka/Nuitka/issues/2850

fix: pyocd work entirety

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

add:freetype support

---

Developer_Manual.rst
README.rst
nuitka/tools/testing/run_nuitka_tests/__main__.py
setup.py

* Add badge to reflect Python support [![Python](https://img.shields.io/pypi/pyversions/Nuitka.svg)](https://badge.fury.io/py/Nuitka)
* Add PyPI badge [![PyPI](https://badge.fury.io/py/Nuitka.svg)](https://badge.fury.io/py/Nuitka)
* Add CII Best Practices badge [![CII Best Practices](https://www.bestpractices.dev/projects/8158/badge)](https://www.bestpractices.dev/en/projects/8158)
* Add OpenSSF Scorecard badge [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/Nuitka/Nuitka/badge)](https://securityscore …

feat: Add badges to reflect 3.12 support

---

nuitka/utils/FileOperations.py

could we merge this into factory, too?
thanks!

Windows: Fix build failure on mapped network drives

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

Yt dlp & co

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

azure cognitiveservices speech

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

The arcade package was bundling megabytes on unnecessary data which is now excluded

improved arcade configuration

---

nuitka/build/static_src/CompiledAsyncgenType.c
nuitka/build/static_src/CompiledCellType.c
nuitka/build/static_src/CompiledCoroutineType.c
nuitka/build/static_src/CompiledFrameType.c
nuitka/build/static_src/CompiledFunctionType.c
nuitka/build/static_src/CompiledGeneratorType.c
nuitka/build/static_src/CompiledMethodType.c
nuitka/build/static_src/MetaPathBasedLoaderResourceReaderFiles.c

Let some functions of *CompiledXXXType.c* in *nuitka/build/static_src* follow the signatures of getter and setter.
#3012 
- ~~[] Ideally new features or fixed regressions ought to be covered via new tests~~
- ~~[] Ideally new or changed features have documentation updates~~
---
- ~~[ ] CompiledCodeHelpers.c~~
- ~~[ ] CompiledGeneratorTypeUncompiledIntegration.c~~

follow getter and setter signatures

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

fixes missing kivymd implicit import

---

nuitka/plugins/standard/standard.nuitka-package.config.yml

driverless-selenium support

---

nuitka/build/static_src/HelpersOperationBinaryMult.c
nuitka/plugins/standard/PlaywrightPlugin.py
nuitka/plugins/standard/standard.nuitka-package.config.yml

Playwright support

---

nuitka/build/static_src/CompiledFrameType.c
nuitka/build/static_src/CompiledFunctionType.c
nuitka/build/static_src/CompiledGeneratorType.c
nuitka/build/static_src/CompiledMethodType.c

#3012
- ~~[ ] Ideally new features or fixed regressions ought to be covered via new tests.~~
- ~~[ ] Ideally new or changed features have documentation updates.~~
--- 
- ~~[ ] TODOs in nuitka/build/static_src/InspectPatcher.c~~
- ~~[ ] TODOs in nuitka/build/static_src/MetaPathBasedLoader.c~~
- ~~[ ] TODOs in nuitka/build/static_src/MetaPathBasedLoaderResourceReader.c~~

follow PyCFunction signatures
