- nuitka/build/SconsInterface.py
Now searches in HKEY_CURRENT_USER registry branch as well.
Caused by "Install for current user only" checkbox in windows installer.
> Scons: Improved Python2 detection on Windows.

- nuitka/freezer/Standalone.py
Before, these directories themselves wouldn't be returned from scanStandardLibraryPath, but they would still be recursively explored. Now, the list contents are replaced in-place, so the contents of these directories are excluded from the walk.
I was having the same issue as http://bugs.nuitka.net/issue292 with the latest version. The "Tools" directory wasn't directly returned, but all the actual scripts inside it still were. This fixes that by modifying the list in-place so it affects the rest of the os.walk.
> Standalone: Fix some ignored directories in the standard lib path.

- tests/basics/BuiltinSuper.py
`sys.version` is a string, so it doesn't make sense to compare it with a tuple.
Found using [pydiatra](https://github.com/jwilk/pydiatra).
> Tests: Fix sys.version comparisons

- nuitka/build/SingleExe.scons
When full path to compiler was provided by CC env var with --show-scons I got:
Scons compiler: Using True
> Fix getExecutablePath() to return path instead of bool

- nuitka/distutils/bdist_nuitka.py
- setup.py
I'm really excited about this usage of nuitka, it provides a very clean and controlled output being able to produce fully compiled wheels ready to distribute and install.
I'd actually started making my own module to integrate nuitka into setuptools before I found what you already had built in.
I've been testing/using this on windows, however this PR doesn't work as is on windows due to `getExecutablePath("nuitka")` failing in my virtualenv. I've been using this branch rebased on #36 where it all works perfectly.
Contents of PR:
* My initial tests of bdist_nuitka resulted in broken wheels with incorrect paths inside the wheel package.
For example, on my pc the package I'm compiling is `C:\Users\anl\src\example_package\setup.py`
When I built the wheel and then open is as a zip there was a …
> Updates to bdist_nuitka

- nuitka/build/SingleExe.scons
If system had too old (default) GCC found_gcc is set to False,
so if another compiler was provided with CC Nuitka used g++ instead.
> Fix compiling with provided GCC through CC env var

- nuitka/distutils/bdist_nuitka.py
I found a merge-fail left over from my previous couple of merge requests, #38 and #36. 
Currently bdist_nuitka fails as it's searching for the binary which was removed in #36
This PR removed the check which is already no longer used.
> Remove obsolete nuitka binary search

- nuitka/freezer/Standalone.py
Don't create unnecessary copies of sets and references.
> optimizations for linux standalone

- .gitignore
Added a line to the .gitignore file in order to ignore Mac OS directory cache data.
> gitignore: ignore Mac OS directory cache

- nuitka/build/SingleExe.scons
Little improvement on top of my previous PR.
I had forgotten to test the implib feature when you specify the `--output-dir`, now it should work fine no matter whether you use `--output-dir` or not. Sorry I didn't test it properly before :/
> Feature implib

- nuitka/Builtins.py
- nuitka/specs/BuiltinParameterSpecs.py
This PR improves the compatibility to pypy and other compilers.
Instead of relying on \_\_builtins\_\_ beeing a dict it imports exceptions and other
builtin stuff from builtins or \_\_builtin\_\_ (python2)
Also it cleans up the \_getBuiltinExceptionNames function.
Note: pypy3 still fails for an other reason.
> Fix/cleanup builtins (for pypy3)

- Developer_Manual.rst
With multiple assignment targets, Python assigns left-to-right.
Fix the example in the documentation to be left-to-right instead of
right-to-left.
Note that Nuitka already handles this correctly as evidenced by running
the following example through nuitka-run:
i = 0
a = [0, 0]
i = a[i] = 1
print(a)
The example first assigns 1 to i and then 1 to a[1], resulting in the
correct output [0, 1], as opposed to [1, 0] which would be output in a
right-to-left-assigning language.
> Developer manual: Fix assignment order in example

- .github/PULL_REQUEST_TEMPLATE.md
- Changelog.rst
- Developer_Manual.rst
- README.rst
- debian/source.lintian-overrides
- nuitka/MainControl.py
- nuitka/build/include/nuitka/calling.h
- nuitka/build/static_src/CompiledFrameType.c
- nuitka/build/static_src/MainProgram.c
- nuitka/codegen/FunctionCodes.py
- nuitka/codegen/VariableCodes.py
- nuitka/nodes/ExpressionBases.py
- nuitka/nodes/LocalsDictNodes.py
- nuitka/nodes/NodeBases.py
- nuitka/nodes/NodeMetaClasses.py
- nuitka/plugins/standard/PmwPlugin.py
- nuitka/tools/testing/measure_construct_performance/__main__.py
- nuitka/tree/InternalModule.py
- nuitka/tree/VariableClosure.py
- nuitka/utils/FileOperations.py
Found via `codespell -q 3 --skip="./nuitka/build/inline_copy,./tests"`
> Fix misc. typos

- nuitka/OptionParsing.py
- nuitka/Options.py
- nuitka/plugins/Plugins.py
This PR adds a new command line flag --user-plugin.
This command line flag is used to load user plugins that are not in the Nuitka source code.
Right now, all plugin source files have to be in the source code of Nuitka.
Adding the flag would allow Nuitka users to write their own plugins.
And the source code of the plugin can be put anywhere.
It's even possible to write per project user plugin.
All UserPluginBase subclasses in the specified file will be imported, unless it's explicitly disabled with flag --plugin-disable
The flag can be used multiple times.
Usage example:
python -m nuitka --module package_test --include-package=package_test --user-plugin my-plugin.py
are Travis tests that cover the most important things however, …
> Add command line flag --user-plugin

- nuitka/plugins/Plugins.py
- nuitka/plugins/user/NumpyPlugin.py
- nuitka/plugins/user/TkinterPlugin.py
Implements two new user plugins for full support of **standalone compiles** of scripts which make use of tkinter and/or numpy.
The **tkinter** plugin is required on Windows only and aims to resolve issue #137. If the plugin is erroneously used on other platforms, it will disable itself and issue an information message.
The **numpy** plugin takes care of compiling numpy scripts successfully in standalone mode. At least on platforms Windows and Linux, numpy standalone compiles will not lead to a usable executable: you will see an exception about a missing …
> include new user plugins TkinterPlugin, NumpyPlugin

- .travis.yml
- nuitka/freezer/Standalone.py
- requirements.txt
Enable internal PE dependency walker on pyd / dll files for Windows environment.
Works with ```--experimental=useInternalDependencyWalker``` and optionally ```--experimental=recursiveInternalDependencies```
On some packages that have multiple dependencies in different site-packages directories, it's also useful to add ```--experimental=recurseIntoSitePackagesDependencyWalker``` in order to check all site-packages for dependent .pyd/.dll files.
Slow dependency walks with depends.exe, also includes a lot of not always used DLLs.
Also fixes missing pythoncom37.dll dependency when using pywin32
Using recurseIntoSitePackagesDependencyWalker may fix other missing DLLs (PyQT5 for example).
are Travis tests that cover the most important …
> Experimental PE file internal dependency walker

- .gitignore
- doc/Doxyfile
- doc/custom.css
> Fixed doc logo size

- nuitka/importing/StandardLibrary.py
Use `os.path.normpath()` on paths found by `getStandardLibraryPaths()` and modules paths inside `isStandardLibraryPath()` to resolve paths that contain relative data like `./` or `../`.
Fixes #264 (using an virtualenv created from an interpreter created by pyenv). See the issue for history and more details.
> Fix non-normpath standard library paths not properly detected as standard library

- nuitka/build/SingleExe.scons
Disable forced Clang compiler mode on FreeBSD/PowerPC
We (FreeBSD) still use GCC on PowerPC architecture.
This is a [local patch](https://svnweb.freebsd.org/ports/head/devel/nuitka/files/patch-nuitka_build_SingleExe.scons) from FreeBSD ports repository.
> Disable forced Clang compiler mode on FreeBSD/PowerPC

- nuitka/__past__.py
- nuitka/containers/odict.py
- nuitka/containers/oset.py
- nuitka/distutils/bdist_nuitka.py
- tests/basics/Classes32.py
Fixes such warnings: `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`.
Despite the fact that it will ease the Python 3.8 compliance, it will specially remove noisy warnings :)
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
> Fix imports from the collections module

- nuitka/tools/quality/pylint/PyLint.py
- nuitka/tools/testing/Common.py
- nuitka/tools/testing/run_nuitka_tests/__main__.py
Improve the code by ensuring file descriptors are closed after `subprocess` calls.
To fix noisy warnings.
```shell
▶ ./bin/check-nuitka-with-pylint
Using concrete python 3.6.8 on x86_64
Working on: ['bin', 'nuitka']
./nuitka/tools/testing/Common.py:739: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
stderr=subprocess.STDOUT,
./nuitka/tools/quality/pylint/PyLint.py:45: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
stderr=open(os.devnull, "w"),
Using PyLint version: 2.2.2
```
> Fix ResourceWarnings when using os.devnull in subprocess calls

- nuitka/plugins/Plugins.py
- nuitka/plugins/standard/PySidePyQtPlugin.py
Inlude OpenGL DLLS on Windows when packaging a PyQt app using QML.
So those new DLLs will be included when using such plugin options:
```
--plugin-enable=qt-plugins=qml
--plugin-enable=qt-plugins=all
```
Fixes #270.
> Include OpenGL DLLs for PyQt QML applications

- Using-Plugin-Options.rst
- nuitka/MainControl.py
- nuitka/plugins/PluginBase.py
- nuitka/plugins/Plugins.py
1. After successful creation of the ``dist`` folder in standalone compilations, a new plugin method ``onStandaloneDistributionFinished`` is called with the distribution folder as parameter. Plugins are free to execute any downstream action.
2. User plugins are now loaded **before** any standard plugins. This allows user plugins to in turn enable standard plugins by themselves.
With these changes, a more complete coverage of the software creation process is possible, while also reducing the need for extra logic to wrap Nuitka. Profiles for various …
> Call to plugins after end of standalone compilations

- nuitka/plugins/standard/PySidePyQtPlugin.py
For qt-plugins, "platforms" plugin is needed not only on Windows, but also on Linux sometimes. Hence, it should be a part of the "sensible" plugin list - at least until we can figure out when is it not necessary (see #299).
> Add "platforms" to the list of "sensible" qt-plugins (temporary fix for #299)

- tests/standalone/FlaskUsing.py
- tests/standalone/GtkUsing.py
- tests/standalone/IdnaUsing.py
- tests/standalone/LxmlUsing.py
- tests/standalone/NumpyUsing.py
- tests/standalone/OpenGLUsing.py
- tests/standalone/PyQt4Plugins.py
- tests/standalone/PyQt4Using.py
- tests/standalone/PyQt5Plugins.py
- tests/standalone/PyQt5SSLSupport.py
- tests/standalone/PyQt5Using.py
- tests/standalone/PySideUsing.py
- tests/standalone/TkInterUsing.py
- tests/standalone/Urllib3Using.py
- tests/standalone/Win32ComUsing.py
- tests/standalone/run_all.py
This PR changes the mechanism in which run_all checks for whether import requirements are satisfied. Now each test file should include a special comment in one of the following formats:
`# nuitka-skip-unless-expression: expression to be evaluated`
(a test would be skipped if this expression evaluated to false)
OR
`# nuitka-skip-unless-imports: module1,module2,...`
(a test would be skipped if any modules are missing)
The new helper function `checkRequirements` inside run_all.py will search for these comments in every test module and do the respective checks as specified.
This new mechanism makes it more clear what imports are required for each test file, as they will be stated in a special comment inside each test file. It also improves code readability and eliminates repetition in …
> run_all.py new special-comment mechanism & Urllib3Using.py

- nuitka/tools/testing/Common.py
- nuitka/tools/testing/SearchModes.py
- tests/basics/run_all.py
- tests/optimizations/run_all.py
- tests/packages/run_all.py
- tests/programs/run_all.py
- tests/standalone/run_all.py
- tests/syntax/run_all.py
> Tests: Added support for "only" mode in Test runners

- nuitka/tools/quality/autoformat/Autoformat.py
- nuitka/utils/FileOperations.py
fixed #334 
After rebasing I was getting another `TypeError` i.e. `TypeError: write() argument must be str, not bytes`
> Quality: Fixed the TypeError in autoformat 

- nuitka/build/static_src/MainProgram.c
Fixes a crash issue when using nuitka on mac os x and parsing sys.argv
(hopefully didn't mess up anything)
> PR for GH-389

- nuitka/plugins/standard/ImplicitImports.py
I checked the changes made in https://github.com/Nuitka/Nuitka/pull/384/commits and I assume this is the way to include SHA224. However, I feel all algorithms should be supported if some are still not included. See my comments: https://github.com/Nuitka/Nuitka/issues/215#issuecomment-500709057
> Add support for SHA224

- .gitignore
- nuitka/tools/testing/Common.py
- nuitka/tools/testing/SearchModes.py
- tests/optimizations/run_all.py
- tests/packages/run_all.py
- tests/standalone/run_all.py
- tests/syntax/run_all.py
- tests/test-runners/run_all.py
> Tests: Add search mode "All"

- nuitka/plugins/standard/ImplicitImports.py
I'am supplying this change individually instead. For some reason, GitHub still thinks I removed and added one extra line ( `yield crypto_module_name + ".Hash._SHA256", True`)
> Add support for SHA384, SHA512

- tests/distutils/example_3/setup.py
I forgot to create a branch for this on my fork, but this is a pretty small changeset so I'm not too worried.
This PR adds a test case in `tests/distutils/example_3`, which provides a very simple example of a [native namespace package](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages). The package itself contains only an `__init__.py`, but that is sufficient for this test case.
Please note that native namespace packages were introduced with **Python 3.3**.
This PR was requested by @kayhayen in #470.
> #470: Add test case for distutils when working with namespace packages

- Developer_Manual.rst
Added git workflow to Dev Manual
> Git workflow added to Developer Manual

- nuitka/MainControl.py
> Fixup_import_module

- nuitka/tools/testing/OutputComparison.py
- tests/PyPI-pytest/README.rst
- tests/PyPI-pytest/packages.json
- tests/PyPI-pytest/run_all.py
Improve automated PyPI test suite
GSoC 2019
> Improve pypi automation

- nuitka/utils/WindowsResources.py
A problem with heavy binaries and depends on user's system
https://github.com/Nuitka/Nuitka/issues/468
**caution!** I could not specify a reason.
> fix FileNotFoundError on adding resources

- nuitka/distutils/bdist_nuitka.py
compile_packages should use '.' separators, however setuptools
allows '/', as seen in package websockets.
> Distutils: Allow slashes in package names

- nuitka/build/SingleExe.scons
The build logs are easier to read when the modules are compiled
in a logical order, and probably this helps to achieve
reproducible builds.
Closes https://github.com/Nuitka/Nuitka/issues/543
> SingleExe.scons: Compile modules in alpha order

- nuitka/build/static_src/MetaPathBasedLoader.c
On Python 3.8, the definition of PyInterpreterState has been
moved to internal headers.
> MetaPathBasedLoader: Python3.8 PyInterpreterState

- nuitka/PostProcessing.py
- nuitka/utils/SharedLibraries.py
Fix **standalone** (i.e. compiled with `--standalone` option) executable rpath (MacOS) for libpython.
For embedded-modules compilation (i.e. `--follow-imports` option) and extension module compilation (i.e. `--module` option), similar problems persist.
This is an hotfix (the issue affects also the `master` branch). Anyway, `develop` is selected as base branch, since the modules affected by this PR changed a lot from `master` to `develop`.
Related to #499 (and #516).
> MacOS standalone rpath issue (Feature/fix issue #499)

- nuitka/Options.py
> Fix --python-flags=no_docstrings without implying no_asserts

- nuitka/Options.py
- nuitka/PythonVersions.py
- nuitka/tools/testing/Common.py
Update the check command for conda envs, to support Python > 3.6. Checking if "Anaconda" is in sys.version string, lead to wrong results for Python ver. > 3.6, as explained in [this](https://stackoverflow.com/a/21282816/2809027) stackoverflow answer.
This is also related to static linking of libpython (in fact only available for conda on non-windows OS).
Related to issue #580 and #95.
Maybe also related to issue #499.
> Update check for conda envs to support Python > 3.6 (issue #580)

- nuitka/distutils/DistutilCommands.py
- tests/distutils/nested_namespaces/a/b/pkg/__init__.py
- tests/distutils/nested_namespaces/setup.py
- tests/distutils/run_all.py
Fixes support of the build_nuitka distutils command for implicit namespace packages nested more than one level deep.
This bug was reported in  #612.
> Distutils nested namespaces

- nuitka/build/SingleExe.scons
- nuitka/freezer/Standalone.py
Clang is the default compiler on the most of platforms supported by OpenBSD. It also has gcc in the base system but the version is too old for the Nuitka requirements and will be deleted in the future.
The changes are needed to support OpenBSD and for the issue #662.
> Add OpenBSD to clang and posix platforms.

- nuitka/utils/SharedLibraries.py
On macOS Python ctypes.util does not contain _get_somename() protected method: https://github.com/python/cpython/blob/3.7/Lib/ctypes/util.py#L70 Due to this Nuitka SharedLibraries:locateDLL fails on macOS.
I stumbled upon this when I was trying to create standalone build from QtQuick Hello World example. 
> Fix, mac ctypes.util does not have _get_soname().

- nuitka/OptionParsing.py
Fixed bad diagnostic message — if user used old plugin options format, like 
«--enable-plugin=numpy=scipy» it gets error message
«Error, plugin options format changed. Use '--enable-plugin=numpy=scipy --help», and catched in bad recursion.
> Fixed bad diagnostic error, if user use old plugin option format like --enable-plugin=numpy=scipy

- nuitka/build/SingleExe.scons
Fixed the output of "objdump" not to be translated
When run with --windows-dependency-tool=pefile option,
_getBinaryArch function does not work properly when the output of "objdump" command is translated
> Fixed the output of "objdump" not to be translated

- nuitka/utils/WindowsResources.py
There is a small typo in nuitka/utils/WindowsResources.py.
Should read `resources` rather than `resourcs`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, resourcs -> resources

- Developer_Manual.rst
Minor documentation fix in developer manual about pip-installing the development requirements from file.
> docs: typo in pip development requirements instructions

- nuitka/freezer/DependsExe.py
The depends executable is downloaded via HTTP and executed without any signature checks,
allowing potential attackers to hijack the download process and execute malicious code.
Since dependencywalker.com offers TLS, we should use it.
> Upgrade insecure depends_url to HTTPS

- README.rst
Fixes typo in README.rst.
I saw typo.
There are Travis and Github Actions tests that cover the most important
cover enough.
> readme: fix typo 'Studion' -> 'Studio'

- nuitka/plugins/standard/ImplicitImports.py
Hello
This PR comes in addition to issue #837. The currently last comment of @EBenkler describes the problem I had, when using the `pandas` module in a project.
Even if I just have
```python
import pandas as pd
```
as a minimum code sample I ran into:
```
import pandas as pd
File "/.../lib/python3.9/site-packages/pandas/__init__.py", line 51, in <module pandas>
from pandas.core.api import (
File "/.../lib/python3.9/site-packages/pandas/core/api.py", line 31, in <module pandas.core.api>
from pandas.core.groupby import Grouper, NamedAgg
File "/.../lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module pandas.core.groupby>
from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
File …
```
> [implicit_import] added 'pandas._libs.window' to 'pandas.core.window'

- nuitka/Options.py
for look for an icon for pythonMAJOR.MINOR.xpm, then pythonMAJOR.xpm
then python.xpm.
on some systems (e.g. ubuntu) python.xpm does not exist.
> onefile icons linux: look for versioned icon file first

- nuitka/freezer/Onefile.py
Quotes the args on the exec statement in AppRun allowing for args with spaces such as filenames
cover enough.
> Allow args w/ spaces in generated AppRun

- nuitka/build/Onefile.scons
- nuitka/build/static_src/OnefileBootstrap.c
- nuitka/freezer/Onefile.py
parse the pe header using MapAndLoad() system function
to find out whether the application has a trailling certificate
rather then assume that the start position of the container is at the
very end of the file.
Close: #1154
> add support for singed onefile-application on windows

- nuitka/Options.py
It fixes a typo in `nuitka/Options.py`, "the non" becomes "none".
No relevant issues, just a typo.
> Fixed typo

- nuitka/plugins/standard/GiPlugin.py
Include typelib files for gi libraries and set up the correct search path.
Following from a discussion on #1011 
I marked it as draft because I still want to improve some things, but the proof of concept seems to work.
I verified with strace to see that the typelib files are loaded from the dist folder.
The typelib files seem to be some kind of database format, but they are not actually libraries, so I opted for the `considerDataFiles` method. 
cover enough.
> Add GI plugin to copy typelib files and set search path

- nuitka/build/SconsCaching.py
Normalize the paths of the downloaded gcc on Windows before comparing them.
When compiling on msys2 (mingw64) and after downloading the proposed gcc.exe I was getting an error that the path does not match.
It seems msys2 is very tolerant about using forward (/) or backward (\) slashes in paths, and in my case they were not matching up, causing a miscompare.
Using `os.path.normpath` normalizes these paths so they can be safely compared.
cover enough.
> Normalize paths before comparing

- nuitka/OptionParsing.py
This was falsely assigned to windows_group.
cover enough.
> OptionParsing: --macos-app-version belongs to macos_group

- nuitka/tools/testing/Common.py
Ignore QT6 dir access in the tests like QT5 dirs are already ignored.
openSUSE test suite failures
> Testing: Allow accessing qt6 dirs

- nuitka/codegen/templates/CodeTemplateCallsPositional.j2
I noticed the code at https://github.com/Nuitka/Nuitka/blob/f4b08e086c2898013a08b74bb45b0ee01f04be8a/nuitka/build/static_src/HelpersCalling2.c#L358 has a useless loop and tried to generate simpler code for that case.
Honestly, I have no idea if C compilers are smart enough these days to detect this, so I don't know whether or not this change will have any net effect.
PS: This is against factory, but I can redo it against develop if you think it's worth it.
> Optimization: avoid loop in generated code for args_count == 1

- nuitka/plugins/standard/ImplicitImports.py
Added missing implicit imports for pycryptodome(x)
* Added missing ciphers
* Added missing hashes
* Modified `.Cipher._raw_*` files inclusion strategy.
They are only triggered by their dependent modules, rather than by `.Util._raw_api`
Fixes #1343
cover enough.
> Added missing implicit imports for pycryptodome(x)

- nuitka/plugins/standard/trio_plugin.py
Adds a plug-in to work around incompatibility between Nuitka and Trio's use of `coro.cr_frame.f_locals` for interrupt handling (#561 and python-trio/trio#1752).
The plug-in works by patching Trio's source code to simply remove that handling. Ctrl+C will still work (at least, there's no reason it shouldn't), but if Trio is running in the main thread then it will be handled less gracefully than without the patch. But at least it will run at all, which it didn't in Nuitka without this patch.
The fact that this is a source code patch means that, unfortunately, it is likely to be fairly fragile to changes in Trio's source code in future versions.
This is based on the "develop" branch, and follows the coding conventions (I ran `autoformat-nuitka-source` and checked with …
> Add Trio plugin

- nuitka/OptionParsing.py
- nuitka/Options.py
- nuitka/freezer/Onefile.py
- nuitka/utils/Utils.py
Adds a flag to set different supported compression algorithms for generating AppImages on Linux (currently only gzip and xz are supported)
xz is currently the default, however it takes a long time to extract and offers little size benefits over gzip in my testing. However rather than replacing it entirely this patch allows the user to manually choose which one they want (although it defaults to gzip as per appimagetool's default)
- [ ✓ ] Correct base branch selected? Should be `develop` branch.
- [ ✓ ] All tests still pass. Check the Developer Manual about `Running the Tests`.
cover enough.
- [ X ] Ideally new features or fixed regressions ought to be …
> WIP: Allow switching compression algorithms for generated AppImages

- nuitka/utils/StaticLibraries.py
Update `isDebianSuitableForStaticLinking` to account for the possibility of non-numeric versions.
I think `sid` is the only string that should ever show up here, but it seems like this check is designed to return `True` in all unexpected situations, so I caught the `ValueError` rather than adding an explicit check for `dist_version == "sid"`.
As far as I can tell there are no existing tests covering this logic, so I didn't update any.
Currently, `nuitka --onefile` crashes on Debian sid because `getLinuxDistribution` returns dist_version `sid` rather than a numeric version number:
```
$ python -m nuitka --onefile hello.py
Nuitka-Options:INFO: Used command line options: --onefile hello.py
File "/home/tortoise/.local/lib/python3.9/site-packages/nuitka/__main …
```
> Fix crash in isDebianSuitableForStaticLinking if version is non-numeric.

- nuitka/Options.py
The module in question is `orderedset`, see: https://github.com/Nuitka/Nuitka/blob/1adf285ad2416876aabe7c474ce9f1ace2344ed9/requirements.txt#L27
> Fix typo in warning message

- .vscode/nuitka-package-config-schema.json
- nuitka/tools/quality/auto_format/YamlFormatter.py
1. add regex check for module-name to schema
2. use the most matching quotes for strings
3. add newline after each entry
> YamlFormatter improvements

- nuitka/plugins/standard/ImplicitImports.py
fix ModuleNotFoundError for 'sklearn.utils.' and 'rapidfuzz.'
please review and merge to upstream
> fix ModuleNotFoundError for 'sklearn.utils.' and 'rapidfuzz.'

- misc/install-git-hooks.py
In all git distro on Win, git.exe and sh.exe are colocated subfolders on same level - git.exe on 'bin' and 'cmd', sh.exe on 'bin'
- [*] Correct base branch selected? Should be `develop` branch.
- [*] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [*] All tests still pass. Check the Developer Manual about `Running the Tests`.
> Fix wrong path to sh.exe (for git.exe) on installing git-hook

- nuitka/freezer/DllDependenciesPosix.py
Nuitka contains a list of known "kernel" shared libraries that are not included.
Since these are not included, we do not need to ensure that they don't contain
relative paths.
Without this patch I got this error (`nuitka3 --standalone diag.py`):
```
FATAL: Error: Found a dependency with a relative path. Was a dependency copied to dist early? linux-vdso.so.1
```
This occured under these conditions:
python -m nuitka --version
1.0.5
Commercial: None
Python: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Sysrescue (based on arch) 9.04
How did you install Nuitka and Python
Arch Linux packages python-3.10.6-1 and nuitka-1.0.5-1 installed through pacman.
No virtualenv used.
> do not check known kernel shared libraries for relative paths

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Updated LooseVersion checks in anti bloat config
Ref: https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/compat/numpy/__init__.py#L11-L17
Generated binary with pandas (1.1.x or 1.0.x) dependency fails because of unknown variable LooseVersion.
```
...
File "/tmp/onefile_3918_1661593705_527601/pandas/__init__.py", line 22, in <module pandas>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "/tmp/onefile_3918_1661593705_527601/pandas/compat/numpy/__init__.py", line 11, in <module pandas.compat.numpy>
NameError: name 'LooseVersion' is not defined
```
things however, …
> Added Pandas compatibility for >= 1.0.0

- .github/workflows/testing.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- nuitka/tools/quality/auto_format/YamlFormatter.py
1. cleanup variable names
2. fix the decision for strings without quotes
3. remove unused `else` in the decision
> YAMLFormatter: cleanup and fix quote decision

- Changelog.rst
FWIW, I feel that many changes in for this release are in the wrong category. E.g several fixes are in the `New Features`, `Optimization` or even `Organisational` parts of the changelog. Also, the `Organisational` section looks more like a `Miscellaneous improvements` section than the usual `Organisational` section.
> fixed typos and duplicated line in changelog

- nuitka/utils/AppDirs.py
The Nixpkgs standard builders sets `HOME` to `/homeless-shelter`. Add this exception.
[Contributing Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md)
cover enough.
> getCacheDir: handle Nixpkgs's default HOME

- nuitka/freezer/DllDependenciesPosix.py
- Fixes `standalone` build for Alpine when `libstdc++` is required.
https://github.com/Nuitka/Nuitka/issues/1893
> Removing from exlude list `libstdc++` on Alpine. Fixes #1893

- nuitka/build/inline_copy/clcache/clcache/caching.py
Apply `decoratorRetries` in clcache to overcome random "access denied" errors tied to anti-virus.
See #1591
> Windows: Retry replace clcache entry after a delay

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Adds the [`grammars` folder](https://github.com/lark-parser/lark/tree/master/lark/grammars) of the [`lark`](https://github.com/lark-parser/lark) package which are imported dynamically and are not embedded naturally by Nuitka.
I stumble upon this issue while trying to make a standalone executable of my [Meta Package Manager](https://github.com/kdeldycke/meta-package-manager) project, which depends on [Click Extra](https://github.com/kdeldycke/click-extra) for CLI configuration loading and colorisation, which depends on [`commentjson`](https://github.com/vaidik/commentjson) to allow commented JSON-based config files, which at last depends on `lark-parser`. …
> Standalone: Added data file for "lark" package.

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This pull request add two implicit dependencies of the sqlalchemy package
A compiled exe that use sqlalchemy with pyodbc or use the default_comparator module raise an import error without this
> Added sqlalchemy implicit dependecies

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This PR remove all numba references from shap packages
Numba is not currently supported in standalone mode. So if you try to run with --noinclude-numba-mode=nofollow it will raise an import error. More info in issue #1990.
> Removed numba references from shap

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This PR removes docstrings dependecies from xgboost.sklearn package only if python flags no_docstrings and no_asserts are given.
It was initiated because xgboost don't work with -OO python flag. Also described in #2006.
> Anti-bloat: Removed xgboost docstring dependencies

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Adds explicit import of `charset_normalizer.md__mypyc` for `charset_normalizer` module.
This PR closes: https://github.com/Nuitka/Nuitka/issues/2020
`charset_normalizer` is missing an import that is only ever imported in a cythonized submodule. Thus, Nuitka cannot see it.
Binaries are properly generated by Nuitka, but their execution ends up with a traceback:
```pytb
File "/tmp/onefile_1583_1674827414_883837/requests/compat.py", line 11, in <module requests.compat>
ModuleNotFoundError: No module named 'chardet'
During handling of the above exception, another exception occurred:
File "/tmp/onefile_1583_1674827414_883837/__main__.py", line 60, in <module>
File "/tmp/onefile_1583_1674827414_883837/__main__.py", line 54, in …
```
> Standalone: Add invisible `md__mypyc` dependency for `charset_normalizer`

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Adds some nuitka package configuration information for the `textual` package.
textual.widgets does some lazy loading tricks with __getattr__
https://github.com/Textualize/textual/blob/main/src/textual/widgets/__init__.py#L52-L67
> Textual package configuration

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Add dll dependencies  for `onnxruntime` (gpu) package.
As #2029 described. 
`> nuitka --list-package-dlls=onnxruntime`
```
Nuitka-Tools:INFO: Checking package directory 'C:\Users\AlanHuang\AppData\Local\Programs\Python\Python38\Lib\site-packages\onnxruntime' ..
C:\Users\AlanHuang\AppData\Local\Programs\Python\Python38\Lib\site-packages\onnxruntime
C:\Users\AlanHuang\AppData\Local\Programs\Python\Python38\Lib\site-packages\onnxruntime\capi        
capi\onnxruntime_providers_cuda.dll
capi\onnxruntime_providers_shared.dll
capi\onnxruntime_providers_tensorrt.dll
```
> Added dll dependencies for onnxruntime (gpu)

- nuitka/__main__.py
Many times, debugging Nuitka troubles (to patch, to find workaround or minimal bugcase), is very convinient to run nuitka on debug mode ('debugpy', 'pydev' — regular python debugging with VSCode).
But for this, every time I  have to patch this way this line for debugging, to disable reexecution (reexecution breaks debugging). So why not make Nuitka debuggable by default?
- [*] Correct base branch selected? Should be `develop` branch.
- [*] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [*] All tests still pass. 
```
python3  ./run-tests  --skip-package-tests --skip-cpython26-tests --skip-cpython27-tests --skip-cpython32-tests --skip-cpython33-tests --skip-cpython34-tests --skip-cpython35-tests  --skip-cpython36-tests --skip-cpython37-tests --skip-cpython38-tests …
```
> Lets not reexecute if we are debugging (vscode-pydev-debugpy)

- nuitka/plugins/standard/standard.nuitka-package.config.yml
PyTorch lightning parses a `version.info` at runtime. version.info is missing when PyTorch lightning is used with nuitka.
This PR ensures that the version.info is copied.
PyTorch lightning usage
cover enough.
Please let me know if i need to update tests / docs (:
> Added support for 'pytorch_lightning'

- nuitka/plugins/standard/standard.nuitka-package.config.yml
As mentioned in my issue #2115 `pymoo` has some implicit dependencies, namely `autograd` and some of its own cython extensions. This PR adds these implicit dependencies.
I tried to follow the [official guide on package configuration](https://nuitka.net/doc/nuitka-package-config.html) and took some inspiration from other modules in the same file. I hope this is the recommended way and I didn't miss anything - otherwise, I'm happy to make corrections.
Due to the `./bin/autoformat-nuitka-source` a few other comments got indented as well. I hope that's alright.
Should some documentation be updated? Is there a list of supported 3rd party modules?
Cheers,
Max
> Add pymoo implicit dependencies to plugins

- README.rst
A `%` was missing in the example for the `--onefile-tempdir-spec` parameter.
This PR was done only to correct the typo.
cover enough.
> Fix missing "%" in README.rst

- nuitka/plugins/standard/standard.nuitka-package.config.yml
- nuitka/utils/MacOSApp.py
During MacOS app bundle generation executable name is set to the application name, which may differ from the actual executable:
[MacOSApp.py:54](https://github.com/Nuitka/Nuitka/blob/36989fb6b35db28132511b947d9b414cb52b6b81/nuitka/utils/MacOSApp.py#LL54C46-L54C46)
```python
infos = OrderedDict(
[
("CFBundleDisplayName", app_name),
("CFBundleName", app_name),
("CFBundleIdentifier", signed_app_name),
("CFBundleExecutable", app_name), #  <- here
("CFBundleInfoDictionaryVersion", "6.0"),
("CFBundlePackageType", "APPL"),
("CFBundleShortVersionString", app_version),
]
)
```
It should fetch the executable name instead.
If this issue occurs, MacOS .app file is marked as corrupted and cannot be launched.
Unfortunately, I couldn't figure out how to add platform-specific test, but I could try adding …
> Fix MacOS app bundle executable name

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Fixes tls-client compiling on differents operating systems. Tested this on both linux and windows, they work. Not sure about MacOS but should work too.  
due to issue #2253 (tls-client only compiling on windows)
> Fix tls-client different operating system dependencies

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This PR updates the standard package config to support AXML parsing libraries ([apkutils](https://gitee.com/kin9-0rz/apkutils), [androguard](https://github.com/androguard/androguard), and [pyaxmlparser](https://github.com/appknox/pyaxmlparser)) by defining the required `public.xml` as a data-file for the dependent packages.
Solves #2289 
cover enough.
> add data-files to AXML parser packages

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This PR updates the DLLs added in the pywebview package, which were changed in version 4.2.
The directories were modified as follows:
- lib/x86 => lib/runtimes/win-x86/native
- lib/x64 => lib/runtimes/win-x64/native
- lib/arm64 => lib/runtimes/win-arm64/native
For more info check the [directory change on pywebview](https://github.com/r0x0r/pywebview/tree/4.2/webview/lib)
I initiated this to make nuitka compatible with pywebview >= 4.2
> Add pywebview DLLs from version 4.2

- nuitka/PythonFlavors.py
This fixes the following error with mingw python 3.11.
nuitka/PythonFlavors.py", line 144, in isMSYS2MingwPython
return "-mingw_" in sysconfig.get_config_var("SO")
TypeError: argument of type 'NoneType' is not iterable
SO config variable in sysconfig was removed in python 3.11. It was
deprecated in Python 3.4 and was suggested for removal in Python 3.5.
See this cpython commit
https://github.com/python/cpython/commit/0860b26a4f7abeb61aad9f4b96de8e78eed8c12a
> Fix usage of deprecated sysconfig variable with mingw

- nuitka/distutils/Build.py
- Adds support for PEP 660 editable installs to nuitka.distutils.Build
- To solve the problem that local project packages cannot be installed in editable mode.
- Related to issue #2356
cover enough.
> Add PEP 660 editable install support for nuitka.distutils.Build

- nuitka/plugins/standard/standard.nuitka-package.config.yml
A fix for a PySide2/6 workaround for Qt signal `connect` function.
And I've changed the function name for clarity.
A signal `connect()` in PySide/Qt actually has one more argument that wasn't covered, although used only occasionally.
Without it, it's possible to encounter exception like this:
```python
File "...", line 33, in <module>
File "...", line 24, in start_app
File "...", line 135, in __enter__
File ".../qtinter/_contexts.py", line 36, in using_asyncio_from_qt
File ".../qtinter/_base_events.py", line 250, in start
File ".../qtinter/_base_events.py", line 268, in _qi_loop_startup
File ".../qtinter/_base_events.py", line 75, in _create_notifier
File ".../qtinter/_base_events.py", line 31, in __init__
File ".../qtinter/bindings.py", line 66, in …
```
> Fixed PySide workaround

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Fixes import error for rapidfuzz 3.X.X(tested 3.0.0, and 3.2.0)
rapidfuzz-test.py code:
```python
from rapidfuzz import fuzz
print(fuzz.ratio("this is a test", "this is a test!")) 
```
Using concrete python 3.11.4(x86_64):
```
nuitka --standalone --windows-force-stderr-spec=errors.txt rapidfuzz-test.py
```
Running the .exe file will trigger the following error:
```python
File "...\rapidfuzz-test.py", line 1, in <module>
File "...\rapidfuzz\__init__.py", line 10, in <module rapidfuzz>
File "...\rapidfuzz\distance\__init__.py", line 6, in <module rapidfuzz.distance>
File "...\rapidfuzz\distance\OSA.py", line 8, in <module rapidfuzz.distance.OSA>
File "...\rapidfuzz\_utils.py", line 105, in fallback_import
File "importlib.py", line 126, in import_module …
```
> Fixed import error for rapidfuzz 3.X.X

- nuitka/reports/Reports.py
This fixes the function for cases where the license is None instead of "UNKNOWN".
> Reports: Fix get_distribution_license() for jinja2 templates

- nuitka/distutils/DistutilCommands.py
This PR is to fix the #2448 issue.
Hey, bro, you thought that issue #2448 was unrelated to Nuitka, so you closed it. However, after a period of breakpoint debugging, I discovered that the cause of this issue lies in a flawed logic within Nuitka's code. 
In the code of the wheel package, at https://github.com/pypa/wheel/blob/e76040b0d970a0fe6211c31888fc929078ba02d9/src/wheel/bdist_wheel.py#L252, when this line of code is executed, the variable `self.plat_name` is still `None`. Its value is initialized later at https://github.com/pypa/wheel/blob/e76040b0d970a0fe6211c31888fc929078ba02d9/src/wheel/bdist_wheel.py#L261. Therefore, at this point, the value of `self.plat_name_supplied` in line 252 is definitely `False`. However, in your Nuitka code, after …
> Fixing the issue #2448 of incorrect platform tag naming for the wheel package.

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Thank you for contributing to Nuitka!
Adds support for the lightning module by including the missing version.info file
The lightning module is not currently able to be used after being built by nuitka
I decided to make this PR in order to address my issue with the lightning module and enable other users to be able to use the module as well. I have based my fix on the discussion on this thread and merged PR
[Add support for …
> Added support for lightning module

- nuitka/plugins/standard/GiPlugin.py
This adds three DLLs to be added by the GI library (soup and secret).
There's a [lot of these](https://lazka.github.io/pgi-docs/) and it would be favorable to have an automatism, but this might be a viable start.
I am trying to package [gtimelog](https://github.com/gtimelog/gtimelog) for Windows, and it is depending on the soup and secret GI modules.
#2471 is related.
- Couldn't get autoformat-nuitka-source to run either in MSys2 nor in an Alpine WSL2 container with venv.  Ran isort and black manually, hope this suffices for now.
- Haven't checked.
- Don't know how I would test this I am afraid.
- Where would I add this?
> Add GI extra dlls: soup, secret

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Add ._noop implicit dependency that winloop needs
fixes 
```
File "C:\Users\Divine\AppData\Local\Temp\ONEFIL~1\main.py", line 1, in <module>
import winloop
File "C:\Users\Divine\AppData\Local\Temp\ONEFIL~1\winloop\__init__.py", line 7, in <module winloop>
File "winloop\\loop.pyx", line 30, in init winloop.loop
ImportError: cannot import name _noop
```
> Added implicit dependency for winloop

- nuitka/plugins/standard/standard.nuitka-package.config.yml
pypi link: https://pypi.org/project/pyocd/
and
https://pypi.org/project/cmsis-pack-manager/
have runed `python3.8 .\bin\autoformat-nuitka-source nuitka`
> Standalone: Add missing resource file for "pyocd" and cmsis_pack_manager

- nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Variables/ListVariable.py
- nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Variables/ListVariable.py
- nuitka/build/inline_copy/lib/scons-4.3.0/SCons/Variables/ListVariable.py
This PR fixes the improper use of `NotImplementedError` with a proper one `NotImplemented` in the SCons library source code.
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [ListVariable.py](https://github.com/Nuitka/Nuitka/tree/develop/nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Variables/ListVariable.py#L77), class: _ListVariable, there is a special method `__lt__` that raises a NotImplementedError. If a special method supporting a binary operation is not implemented it should [return NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented). On the other hand, …
> Fixed Improper Method Call: Replaced `NotImplementedError`

- nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Platform/win32.py
- nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Platform/win32.py
This PR fixes an unsafe method (mktemp) with a safer one (mkstemp). [Using an unsafe API to create temporary files (CWE-377)](https://cwe.mitre.org/data/definitions/377.html) can leave application and data vulnerable to attack.
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [win32.py](https://github.com/Nuitka/Nuitka/tree/develop/nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Platform/win32.py#L133), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR …
> Fixed Improper Method Call: Replaced `mktemp`

- nuitka/distutils/DistutilCommands.py
The `tool.nuitka` field from `pyproject.toml` gets loaded as a nested dict into the `toml_options` variable. 
Therefore `toml_options['tool.nuitka']` is empty and instead we need to access `toml_options['tool']['nuitka']`.
Despite using `v1.9.4` which includes d249f42645b16a0036d5730b24faffcf317fee07, nuitka didn't recognize the `tool.nuitka` field in my `pyproject.toml`.
Note: I didn't run the test suite for this small change, however tested on a local repo that this fixed my issue.
> Fix bug: incorrectly access `pyproject.toml` `tool.nuitka` field

- nuitka/PythonVersions.py
- nuitka/build/Backend.scons
This PR allows Nuitka to work with virtualenvs created from not-installed, self-compiled Python version on Unix systems (tested and works on macOS).
This PR is related to issue #2611.
---
NOTE: I successfully ran all the tests on Linux. On macOS they fail (either on my branch and on `develop`): 
```
+Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
```
> Handles virtualenv of not installed, self-compiled Python versions

- nuitka/utils/StaticLibraries.py
It adds a new search path to get the static libpython when running in a pyenv.
I was messing around with running nuitka with python installed with pyenv for a github action (https://github.com/Eeems-Org/remarkable-nuitka-build-action) and it was failing to compile when `--static-libpython` was set to `yes` due to not finding the `libpython*.a` file.
> Fix --static-libpython=yes in pyenv

- nuitka/OptionParsing.py
- nuitka/Options.py
before:
```
Nuitka-Scons:INFO: Compiled 203 C files using clcache with 162 cache hits and 41 cache misses.
Nuitka-Postprocessing:INFO: File 'assets\textures\icon.png' is not in Windows icon format, converting to it.
Nuitka-Postprocessing:INFO: Adding 7 icon(s) from icon file 'assets/textures/icon.png'.
Nuitka-Postprocessing:INFO: File 'assets\textures\icon.png' is not in Windows icon format, converting to it.
Nuitka-Postprocessing:INFO: Adding 7 icon(s) from icon file 'assets/textures/icon.png'.
Nuitka-Postprocessing:INFO: File 'assets\textures\icon.png' is not in Windows icon format, converting to it.
Nuitka-Postprocessing:INFO: Adding 7 icon(s) from icon file 'assets/textures/icon.png'.
Nuitka-Options:INFO: Included data file 'config\lndl-logger.toml' due to specified data dir …
```
> Fix: nuitka will not dectect icon not belong to its platform

- nuitka/plugins/standard/standard.nuitka-package.config.yml
fixes #44 
works against
```
from pony.orm.core import *
db = Database()
class Numbers(db.Entity):
_table_ = "Numbers"
id = PrimaryKey(int, auto=True)
int8 = Required(int, size=8)  # TINYINT
int16 = Required(int, size=16)  # SMALLINT
int24 = Required(int, size=24)  # MEDIUMINT
int32 = Required(int, size=32)  # INTEGER
int64 = Required(int, size=64)  # BIGINT
uint8 = Required(int, size=8, unsigned=True)  # TINYINT UNSIGNED
uint16 = Required(int, size=16, unsigned=True)  # SMALLINT UNSIGNED
uint24 = Required(int, size=24, unsigned=True)  # MEDIUMINT UNSIGNED
uint32 = Required(int, size=32, unsigned=True)  # INTEGER UNSIGNED
sql_debug(True)  # Output all SQL queries to stdout
db.bind("sqlite", "test_numbers.sqlite", create_db=True) # TESTED BY KRRT
db.drop_table("Numbers", if_exists=True, …
```
> PonyORM implicit dependencies

- nuitka/build/SconsInterface.py
It generate with not very useful `scons-report.txt`, very useful `scons-debug.sh` or `scons-debug.bat` (for Win), that simplified debugging of Scons build process, experimenting with compiler switches, fastly catching nontrivial bugs in build environment without need to run Nuitka part of code generation as discussed here https://github.com/Nuitka/Nuitka/issues/792#issuecomment-1601361367
Unfortunately, I still cannot see a reliable way to do it as a plugin, to fix exactly that environment variables and switches from SCons Pipeline, without putting this couple of lines closer (just before) SCons pipeline call.
https://github.com/Nuitka/Nuitka/issues/792#issuecomment-1601361367
- [v] All tests still pass. Check the Developer Manual about `Running the Tests`. 
- Actually, some python 2.7 / …
> Generate Scons Pipeline Debug Script

- nuitka/plugins/standard/standard.nuitka-package.config.yml
- nuitka/utils/FileOperations.py
Fix working with UNC paths (Samba folders / Shared VM folders / etc)
https://github.com/Nuitka/Nuitka/issues/2767
https://github.com/Nuitka/Nuitka/issues/2767
Now it works on windows both with UNC paths mapped to folder and even unmapped UNC paths (`\\somecomp\somefolder`). 
- [V] All tests still pass. 
- On windows tests only on Python 3.12 (several hours)
- On Linux failed on Python 2, but looks python 2 broken on my box
I think no documentation changes needed.
About tests, theoretically in possible checking working UNC paths on Windows, I can try to write it if needed, but not sure that possible to cover nontrivial cases (Windows Sandox, Hyper-V shared folders, etc).
> Fix working with UNC paths and reparse points on Windows

- nuitka/utils/CStrings.py
📈 Performance improved by **`104%`** (**`1.04x` faster**)
⏱️ Runtime went down from **`530.40μs`** to **`260.40μs`**
<details>
<summary>(click to show)</summary>
Here the basic idea is that we reduce the number of function calls since each call has its own overhead. Instead of loop through each character and repeatedly call the regular expression function, we should perform the re.sub operation on the entire string. Here is a faster version.
In this revised version, re.sub will only be called once on the entire string, instead of once per character in the original string. This significantly reduces the number of function calls, yielding a performance improvement.
</details>
The new optimized code was tested for correctness. The results are listed below.
<details>
<summary>(click to show …
> ⚡️ Speed up `encodePythonIdentifierToC()` by 104% in `nuitka/utils/CStrings.py`

- nuitka/Options.py
Swaps "disable" and "force" in the warning message for the deprecated --enable-console and --disable-console flags
The warning currently says this:
"The old console option '--enable-console' should not be given anymore, use '--windows-console-module=disable' instead. It also has the extra mode 'attach' to consider."
It should say --windows-console-module=force when the --enable-console flag is present and vice versa.
> Fix --enable-console warning message

- nuitka/utils/FileOperations.py
`drive` has a value of something like `"Y:"` so when we prepend this to a subpath, which will not include and leading slash, we need to add the path separator.
> fix Windows build failure on mapped network drives

- nuitka/plugins/standard/standard.nuitka-package.config.yml
Adds the [`data` folder](https://github.com/nexB/license-expression/tree/main/src/license_expression/data) of the [`license-expression`](https://github.com/nexB/license-expression) package is where the license database is stored. While seems to be available is the source distribution, Nuitka has not enough metadata to import it naturally.
I stumble upon this issue while trying to make a standalone executable of my [Meta Package Manager](https://github.com/kdeldycke/meta-package-manager) project, which depends on [`cyclonedx-python-lib`](https://github.com/CycloneDX/cyclonedx-python-lib) for SBOM export, itself depending on `license-expression`.
If [compiling of my CLI ends up without any error](https://github.com/kdeldycke/meta-package-manager/actions/runs/10150356524/job/28067304207#step: …
> Add data file for `license-expression` package

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This fix the bad ID for the `license-expression` package introduced in #3033.
I'd like to apologise, I mixed up my local copies of Nuitka fork and venv, so I pushed my previous #3033 PR with the wrong package ID. 🙇
I triple-checked this PR really fix the issue with `license-expression` package.
> Typo in `license_expression` package ID

- nuitka/plugins/standard/standard.nuitka-package.config.yml
This pr removes all the numba references in the latest shap package version
Newer versions of shap uses njit decorator instead of @jit. Updating the yaml to remove this new references when 'not use_numba' is specified
> Standalone: removed numba references from shap

- nuitka/plugins/standard/standard.nuitka-package.config.yml
[pygame-ce](https://github.com/pygame-community/pygame-ce) is a fork of pygame that uses a custom SDL Image build. For whatever reason, `libpng16-16.dll` and `libjpeg-62.dll` don't get copied into the build. I'm hoping this is a temporary fix (I tested that this seems to still work fine with the original). We have our own issue [here](https://github.com/pygame-community/pygame-ce/issues/2954) that I'm hoping we can eventually resolve on the library side, rather than Nuitka's side. But for now, this is the only solution I've come …
> pygame-ce compat with weird missing dlls

- nuitka/plugins/standard/standard.nuitka-package.config.yml
https://github.com/python-trio/trio/commit/69819e37d0f02f41a38461cb338b96127caa2909 broke Nuitka's workaround. This PR removes the added assert in `trio._core._run`.
> Fix support for "trio" versions >= 0.26.1

- nuitka/build/SconsCaching.py
- nuitka/utils/FileOperations.py
This PR plans to address the encoding issues in ccache logs.
I have done some simple tests locally and found ccache does not treat all encoding consistently in their logs (probably because of some unspecified behaviors in `std::filesystem::path::string` but I didn't investigate it further). My tests also find that all command and result lines (with which we are only concerned if I understand the code correctly) are encoded with local encoding.
Given the inconsistent in the log, I suggest we decode the log using the local …
> fix: tolerate decoding error in ccache logs

- nuitka/plugins/standard/standard.nuitka-package.config.yml
pyav >= 13.1.0 adds `av.opaque` which is imported by `av.frame` and `av.packet`. The missing implicit import causes programs that use pyav to crash with `No module named "av.opaque"`
> Fix missing av.opaque implicit import in pyav >= 13.1.0

- README.rst
Corrected minor spelling and grammatical errors in the README for improved clarity and professionalism. No functional changes to the codebase.
> Fix typos in README file
